baseURL = "/"
languageCode = "en-us"
title = "Alessandro Minoccheri"
theme= "hugo-nuo"

[params]
    avatar= "img/alessandro_minoccheri.jpg"
    email = "alessandro.minoccheri@gmail.com"
    github = "AlessandroMinoccheri"
    twitter = "minompi"
    linkedin = "alessandro-minoccheri-68756598"
